/* tslint:disable */
/* eslint-disable */
/**
 * USE_NEXT PoC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsHealth
 */
export interface ModelsHealth {
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    oclResult: string;
}

/**
 * Check if a given object implements the ModelsHealth interface.
 */
export function instanceOfModelsHealth(value: object): value is ModelsHealth {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('oclResult' in value) || value['oclResult'] === undefined) return false;
    return true;
}

export function ModelsHealthFromJSON(json: any): ModelsHealth {
    return ModelsHealthFromJSONTyped(json, false);
}

export function ModelsHealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsHealth {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'oclResult': json['oclResult'],
    };
}

export function ModelsHealthToJSON(json: any): ModelsHealth {
    return ModelsHealthToJSONTyped(json, false);
}

export function ModelsHealthToJSONTyped(value?: ModelsHealth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'oclResult': value['oclResult'],
    };
}

