/* tslint:disable */
/* eslint-disable */
/**
 * USE_NEXT PoC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ModelsHealth,
    ModelsHealthFromJSON,
    ModelsHealthToJSON,
} from '../models/ModelsHealth';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

/**
 * 
 */
export class ModelsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getModelsHealth without sending the request
     */
    async getModelsHealthRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/models/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Placeholder business endpoint; evaluates one OCL expression via use-core
     */
    async getModelsHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsHealth>> {
        const requestOptions = await this.getModelsHealthRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsHealthFromJSON(jsonValue));
    }

    /**
     * Placeholder business endpoint; evaluates one OCL expression via use-core
     */
    async getModelsHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsHealth> {
        const response = await this.getModelsHealthRaw(initOverrides);
        return await response.value();
    }

}
