/* tslint:disable */
/* eslint-disable */
/**
 * USE_NEXT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type OclEvaluationRequest,
    OclEvaluationRequestFromJSON,
    OclEvaluationRequestToJSON,
} from '../models/OclEvaluationRequest';
import {
    type OclEvaluationResult,
    OclEvaluationResultFromJSON,
    OclEvaluationResultToJSON,
} from '../models/OclEvaluationResult';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface EvaluateOclRequest {
    /**
     * 
     */
    oclEvaluationRequest: OclEvaluationRequest;
}

/**
 * 
 */
export class OclApi extends runtime.BaseAPI {

    /**
     * Creates request options for evaluateOcl without sending the request
     */
    async evaluateOclRequestOpts(requestParameters: EvaluateOclRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['oclEvaluationRequest'] == null) {
            throw new runtime.RequiredError(
                'oclEvaluationRequest',
                'Required parameter "oclEvaluationRequest" was null or undefined when calling evaluateOcl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/ocl/evaluate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OclEvaluationRequestToJSON(requestParameters['oclEvaluationRequest']),
        };
    }

    /**
     * Evaluates an OCL expression against the fixed server-side model
     */
    async evaluateOclRaw(requestParameters: EvaluateOclRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OclEvaluationResult>> {
        const requestOptions = await this.evaluateOclRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OclEvaluationResultFromJSON(jsonValue));
    }

    /**
     * Evaluates an OCL expression against the fixed server-side model
     */
    async evaluateOcl(requestParameters: EvaluateOclRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OclEvaluationResult> {
        const response = await this.evaluateOclRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
