/* tslint:disable */
/* eslint-disable */
/**
 * USE_NEXT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CsrfToken
 */
export interface CsrfToken {
    /**
     * 
     */
    headerName: string;
    /**
     * 
     */
    token: string;
}

/**
 * Check if a given object implements the CsrfToken interface.
 */
export function instanceOfCsrfToken(value: object): value is CsrfToken {
    if (!('headerName' in value) || value['headerName'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function CsrfTokenFromJSON(json: any): CsrfToken {
    return CsrfTokenFromJSONTyped(json, false);
}

export function CsrfTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CsrfToken {
    if (json == null) {
        return json;
    }
    return {
        
        'headerName': json['headerName'],
        'token': json['token'],
    };
}

export function CsrfTokenToJSON(json: any): CsrfToken {
    return CsrfTokenToJSONTyped(json, false);
}

export function CsrfTokenToJSONTyped(value?: CsrfToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headerName': value['headerName'],
        'token': value['token'],
    };
}

