/* tslint:disable */
/* eslint-disable */
/**
 * USE_NEXT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OclEvaluationResult
 */
export interface OclEvaluationResult {
    /**
     * Result in USE notation; longer results are cut off server-side
     */
    result: string;
}

/**
 * Check if a given object implements the OclEvaluationResult interface.
 */
export function instanceOfOclEvaluationResult(value: object): value is OclEvaluationResult {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function OclEvaluationResultFromJSON(json: any): OclEvaluationResult {
    return OclEvaluationResultFromJSONTyped(json, false);
}

export function OclEvaluationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): OclEvaluationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'],
    };
}

export function OclEvaluationResultToJSON(json: any): OclEvaluationResult {
    return OclEvaluationResultToJSONTyped(json, false);
}

export function OclEvaluationResultToJSONTyped(value?: OclEvaluationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
    };
}

