/* tslint:disable */
/* eslint-disable */
/**
 * USE_NEXT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OclEvaluationRequest
 */
export interface OclEvaluationRequest {
    /**
     * 
     */
    expression: string;
}

/**
 * Check if a given object implements the OclEvaluationRequest interface.
 */
export function instanceOfOclEvaluationRequest(value: object): value is OclEvaluationRequest {
    if (!('expression' in value) || value['expression'] === undefined) return false;
    return true;
}

export function OclEvaluationRequestFromJSON(json: any): OclEvaluationRequest {
    return OclEvaluationRequestFromJSONTyped(json, false);
}

export function OclEvaluationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OclEvaluationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expression': json['expression'],
    };
}

export function OclEvaluationRequestToJSON(json: any): OclEvaluationRequest {
    return OclEvaluationRequestToJSONTyped(json, false);
}

export function OclEvaluationRequestToJSONTyped(value?: OclEvaluationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expression': value['expression'],
    };
}

